In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('../../data/external/london_houses_data.csv')

In [3]:
data.sample(5)

,fullAddress,postcode,country,outcode,latitude,longitude,bathrooms,bedrooms,floorAreaSqM,livingRooms,...,saleEstimate_upperPrice,saleEstimate_confidenceLevel,saleEstimate_ingestedAt,saleEstimate_valueChange.numericChange,saleEstimate_valueChange.percentageChange,saleEstimate_valueChange.saleDate,history_date,history_price,history_percentageChange,history_numericChange
95622,"Flat 104, Harley House, Marylebone Road, Londo...",NW1 5HN,England,NW1,51.523458,-0.150797,3.0,3.0,229.0,1.0,...,4165000.0,MEDIUM,2024-10-07T13:26:59.894Z,3087000.0,441.000000,2018-01-18,1999-06-29,187500,NaN,NaN
153589,"25 Taymount Grange, Taymount Rise, London, SE2...",SE23 3UH,England,SE23,51.437779,-0.058691,1.0,3.0,106.0,1.0,...,599000.0,HIGH,2024-10-07T13:26:59.894Z,39000.0,7.330827,2021-03-26,2003-01-31,220000,238.461538,155000.0
262640,"Apartment 81, Asquith House, 1 Segrave Walk, L...",W2 1BN,England,W2,51.521355,-0.173099,NaN,NaN,78.0,NaN,...,1264000.0,HIGH,2024-10-07T13:26:59.894Z,-74000.0,-5.790297,2022-11-11,2022-11-11,1278000,NaN,NaN
256084,"Flat E, 25 Charles Street, London, W1J 5DT",W1J 5DT,England,W1J,51.507460,-0.149096,1.0,NaN,48.0,1.0,...,1057000.0,LOW,2024-10-07T13:26:59.894Z,81000.0,10.125000,2022-07-08,2022-07-08,800000,14.285714,100000.0
23182,"106 Teesdale Street, London, E2 6PU",E2 6PU,England,E2,51.530217,-0.061522,2.0,2.0,95.0,1.0,...,789000.0,HIGH,2024-10-07T13:26:59.894Z,2000.0,0.322743,2023-10-10,2017-12-11,698500,179.400000,448500.0

In [4]:

print('=======================================================')
print('============== SOME RELEVANT INFORMATION ==============')
print('=======================================================\n')
print('~> Shape of Dataset:', data.shape)
print('~> NÂº Rows:', data.shape[0])
print('~> NÂº Columns:', data.shape[1])
print('\n~> Null values:', [x for x in data.isnull().sum()])
print('\n~> Columns:', data.columns.tolist(), '\n')
print('==================================================')
print('================ DTYPES INFORMATION ==============')
print('==================================================\n')
print('\n~> Dtypes:', [x for x in data.dtypes])
print('\n~> String Columns:', data.select_dtypes('object').columns.tolist())
print('\n~> Float Columns:', data.select_dtypes('float64').columns.tolist())
print('\n~> Integer Columns:', data.select_dtypes('int64').columns.tolist())

=======================================================
============== SOME RELEVANT INFORMATION ==============
=======================================================

~> Shape of Dataset: (282872, 28)
~> NÂº Rows: 282872
~> NÂº Columns: 28

~> Null values: [0, 0, 0, 0, 0, 0, 51103, 26218, 15812, 39135, 6311, 675, 58311, 1222, 1222, 1222, 549, 549, 549, 549, 549, 549, 549, 549, 0, 0, 122213, 122213]

~> Columns: ['fullAddress', 'postcode', 'country', 'outcode', 'latitude', 'longitude', 'bathrooms', 'bedrooms', 'floorAreaSqM', 'livingRooms', 'tenure', 'propertyType', 'currentEnergyRating', 'rentEstimate_lowerPrice', 'rentEstimate_currentPrice', 'rentEstimate_upperPrice', 'saleEstimate_lowerPrice', 'saleEstimate_currentPrice', 'saleEstimate_upperPrice', 'saleEstimate_confidenceLevel', 'saleEstimate_ingestedAt', 'saleEstimate_valueChange.numericChange', 'saleEstimate_valueChange.percentageChange', 'saleEstimate_valueChange.saleDate', 'history_date', 'history_price', 'history_percentageChange', 'history_numericChange']

==================================================
================ DTYPES INFORMATION ==============
==================================================


~> Dtypes: [dtype('O'), dtype('O'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('float64'), dtype('float64'), dtype('O'), dtype('O'), dtype('int64'), dtype('float64'), dtype('float64')]

~> String Columns: ['fullAddress', 'postcode', 'country', 'outcode', 'tenure', 'propertyType', 'currentEnergyRating', 'saleEstimate_confidenceLevel', 'saleEstimate_ingestedAt', 'saleEstimate_valueChange.saleDate', 'history_date']

~> Float Columns: ['latitude', 'longitude', 'bathrooms', 'bedrooms', 'floorAreaSqM', 'livingRooms', 'rentEstimate_lowerPrice', 'rentEstimate_currentPrice', 'rentEstimate_upperPrice', 'saleEstimate_lowerPrice', 'saleEstimate_currentPrice', 'saleEstimate_upperPrice', 'saleEstimate_valueChange.numericChange', 'saleEstimate_valueChange.percentageChange', 'history_percentageChange', 'history_numericChange']

~> Integer Columns: ['history_price']

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 282872 entries, 0 to 282871
Data columns (total 28 columns):
 #   Column                                     Non-Null Count   Dtype
---  ------                                     --------------   -----
 0   fullAddress                                282872 non-null  object
 1   postcode                                   282872 non-null  object
 2   country                                    282872 non-null  object
 3   outcode                                    282872 non-null  object
 4   latitude                                   282872 non-null  float64
 5   longitude                                  282872 non-null  float64
 6   bathrooms                                  231769 non-null  float64
 7   bedrooms                                   256654 non-null  float64
 8   floorAreaSqM                               267060 non-null  float64
 9   livingRooms                                243737 non-null  float64
 10  tenure                                     276561 non-null  object
 11  propertyType                               282197 non-null  object
 12  currentEnergyRating                        224561 non-null  object
 13  rentEstimate_lowerPrice                    281650 non-null  float64
 14  rentEstimate_currentPrice                  281650 non-null  float64
 15  rentEstimate_upperPrice                    281650 non-null  float64
 16  saleEstimate_lowerPrice                    282323 non-null  float64
 17  saleEstimate_currentPrice                  282323 non-null  float64
 18  saleEstimate_upperPrice                    282323 non-null  float64
 19  saleEstimate_confidenceLevel               282323 non-null  object
 20  saleEstimate_ingestedAt                    282323 non-null  object
 21  saleEstimate_valueChange.numericChange     282323 non-null  float64
 22  saleEstimate_valueChange.percentageChange  282323 non-null  float64
 23  saleEstimate_valueChange.saleDate          282323 non-null  object
 24  history_date                               282872 non-null  object
 25  history_price                              282872 non-null  int64
 26  history_percentageChange                   160659 non-null  float64
 27  history_numericChange                      160659 non-null  float64
dtypes: float64(16), int64(1), object(11)
memory usage: 60.4+ MB

In [6]:
FEATURE_COLS = data.select_dtypes('float64').columns.tolist() # vou usar somente as colunas float
TARGET = 'history_price'

In [7]:
X = data[FEATURE_COLS].drop(columns=['saleEstimate_valueChange.percentageChange', 'history_percentageChange'])

In [8]:
y = data[TARGET]

In [9]:
print('X (shape): ', X.shape)
print('y (shape): ', y.shape)

X (shape):  (282872, 14)
y (shape):  (282872,)

### Tratanto de outliers (RemoÃ§Ã£o por quantis)

In [10]:
# ANTES DA REMOÃ‡ÃƒO

q90 = y.quantile(0.90)
q95 = y.quantile(0.95)
q99 = y.quantile(0.99)
q01 = y.quantile(0.01)
q05 = y.quantile(0.05)
q10 = y.quantile(0.10)

ymin = y.min()
ymax = y.max()
ystd = y.std()
median = y.median()
ampl = ymax - ymin

print('=======================================================')
print('====================== QUANTILES ======================')
print('=======================================================\n')
print('90%: ', q90)
print('95%: ', q95)
print('99%: ', q99)
print('01%: ', q01)
print('05%: ', q05)
print('10%: \n\n\n', q10)
print('=======================================================')
print('====================== QUANTILES ======================')
print('=======================================================\n')
print('Min: ', ymin)
print('Max: ', ymax)
print('Std: ', ystd)
print('Median: ', median)
print('Amplitude: ', ampl)

=======================================================
====================== QUANTILES ======================
=======================================================

90%:  1180000.0
95%:  1730000.0
99%:  4330000.0
01%:  42071.0
05%:  79995.0
10%:


 122500.0
=======================================================
====================== QUANTILES ======================
=======================================================

Min:  10000
Max:  100000000
Std:  1263486.0699584687
Median:  397000.0
Amplitude:  99990000

In [11]:
# removendo outliers

lower_bound = y.quantile(0.10)  # 10%
upper_bound = y.quantile(0.90)  # 90%

mask = (y >= lower_bound) & (y <= upper_bound)
X = X[mask]
y = y[mask]

In [12]:
# apÃ³s a remoÃ§Ã£o dos outliers

q90 = y.quantile(0.90)
q95 = y.quantile(0.95)
q99 = y.quantile(0.99)
q01 = y.quantile(0.01)
q05 = y.quantile(0.05)
q10 = y.quantile(0.10)

ymin = y.min()
ymax = y.max()
ystd = y.std()
median = y.median()
ampl = ymax - ymin

print('=======================================================')
print('====================== QUANTILES ======================')
print('=======================================================\n')
print('90%: ', q90)
print('95%: ', q95)
print('99%: ', q99)
print('01%: ', q01)
print('05%: ', q05)
print('10%: \n\n\n', q10)
print('=======================================================')
print('====================== QUANTILES ======================')
print('=======================================================\n')
print('Min: ', ymin)
print('Max: ', ymax)
print('Std: ', ystd)
print('Median: ', median)
print('Amplitude: ', ampl)

=======================================================
====================== QUANTILES ======================
=======================================================

90%:  817000.0
95%:  950000.0
99%:  1125000.0
01%:  128000.0
05%:  150000.0
10%:


 178000.0
=======================================================
====================== QUANTILES ======================
=======================================================

Min:  122500
Max:  1180000
Std:  242946.3035517508
Median:  397500.0
Amplitude:  1057500

In [13]:
print('X (shape): ', X.shape)
print('y (shape): ', y.shape)

X (shape):  (226453, 14)
y (shape):  (226453,)

### Tratando de Outliers (RemoÃ§Ã£o por Z-Score)

In [71]:
from scipy.stats import zscore

y_zscores = zscore(y)
mask = (abs(y_zscores) < 4)  # MantÃ©m valores dentro de 4 desvios padrÃ£o
X = X[mask]
y = y[mask]

In [72]:
# POR Z-SCORE

q90 = y.quantile(0.90)
q95 = y.quantile(0.95)
q99 = y.quantile(0.99)
q01 = y.quantile(0.01)
q05 = y.quantile(0.05)
q10 = y.quantile(0.10)

ymin = y.min()
ymax = y.max()
ystd = y.std()
median = y.median()
ampl = ymax - ymin

print('=======================================================')
print('====================== QUANTILES ======================')
print('=======================================================\n')
print('90%: ', q90)
print('95%: ', q95)
print('99%: ', q99)
print('01%: ', q01)
print('05%: ', q05)
print('10%: \n\n\n', q10)
print('=======================================================')
print('====================== QUANTILES ======================')
print('=======================================================\n')
print('Min: ', ymin)
print('Max: ', ymax)
print('Std: ', ystd)
print('Median: ', median)
print('Amplitude: ', ampl)

=======================================================
====================== QUANTILES ======================
=======================================================

90%:  1111055.8000000033
95%:  1575000.0
99%:  2995000.0
01%:  42000.0
05%:  79500.0
10%:


 121500.0
=======================================================
====================== QUANTILES ======================
=======================================================

Min:  10000
Max:  4414600
Std:  544348.7197819051
Median:  393942.0
Amplitude:  4404600

In [74]:
print('X (shape): ', X.shape)
print('y (shape): ', y.shape)

X (shape):  (280139, 14)
y (shape):  (280139,)

## ComparaÃ§Ã£o de EstatÃ­sticas ApÃ³s RemoÃ§Ã£o de Outliers

| MÃ©trica               | Antes da RemoÃ§Ã£o         | RemoÃ§Ã£o por Quantis     | RemoÃ§Ã£o por Z-Score      |
|-----------------------|--------------------------|--------------------------|--------------------------|
| **Min**               | 10.000                  | 79.995                  | 10.000                  |
| **Max**               | 100.000.000            | 1.730.000               | 4.414.660               |
| **Amplitude**         | 99.990.000             | 1.650.005               | 4.404.600               |
| **Desvio PadrÃ£o**     | 1.263.486              | 331.227                 | 544.348                 |
| **Mediana**           | 397.000                | 397.000                 | 393.942                 |
| **90% Quantil**       | 1.180.000              | 950.000                 | 1.111.055,80                 |
| **95% Quantil**       | 1.730.000              | 1.206.932               | 1.575.000               |
| **99% Quantil**       | 4.330.000              | 1.575.000               | 2.995.000               |
| **01% Quantil**       | 42.071                 | 86.310                  | 42.000                  |
| **05% Quantil**       | 79.995                 | 119.000                 | 79.500                 |
| **10% Quantil**       | 122.500                | 150.000                 | 121.500                 |
| **NÃºmero de Dados Restantes** | 282.872                | 254.606                 | 280.139                 |
| **Perda de Dados (%)**| **0%**                 | **9,99%**               | **0,97%**              |

---

## ObservaÃ§Ãµes
### Antes da RemoÃ§Ã£o
- Dados extremamente dispersos, com amplitude e desvio padrÃ£o elevados.
- Valores extremos afetavam a consistÃªncia dos dados.

### RemoÃ§Ã£o por Quantis
- Menor perda de dados em comparaÃ§Ã£o Ã  abordagem por z-score.
- Dados mais consistentes, com grande reduÃ§Ã£o na amplitude e desvio padrÃ£o.
- PreservaÃ§Ã£o da mediana, indicando que os dados centrais nÃ£o foram muito afetados.

### RemoÃ§Ã£o por Z-Score
- Menor perda de dados (0,97%) em comparaÃ§Ã£o aos quantis.
- NÃ£o Ã© responsÃ¡vel, devido ao assimetria dos dados.

---

## ConclusÃ£o
A remoÃ§Ã£o por quantis apresenta uma menor perda de dados, o que pode ser mais vantajoso dependendo do contexto e da necessidade de maior volume de dados para o modelo.

### Salvando os dados

In [96]:
X.to_csv('../../data/processed/train.csv', index=False)
y.to_csv('../../data/processed/test.csv', index=False)